import product1Img from "../assets/hero.webp";

export const products = [
  {
    id: 1,
    name: "Pomada Modeladora",
    description: "Fixação forte para um estilo duradouro.",
    price: "€ 15,99",
    image: product1Img,
  },
  {
    id: 2,
    name: "Óleo para Barba",
    description: "Hidratação e brilho natural para a sua barba.",
    price: "€ 18,50",
    image: product1Img,
  },
  {
    id: 3,
    name: "Bálsamo Pós-Barba",
    description: "Acalma e refresca a pele após o barbear.",
    price: "€ 14,75",
    image: product1Img,
  },
  {
    id: 4,
    name: "Gel Fixador",
    description: "Fixação média com acabamento natural.",
    price: "€ 12,90",
    image: product1Img,
  },
  {
    id: 5,
    name: "Cera para Cabelo",
    description: "Modelagem flexível com brilho suave.",
    price: "€ 16,20",
    image: product1Img,
  },
  {
    id: 6,
    name: "Espuma de Barbear",
    description: "Suaviza e protege a pele durante o barbear.",
    price: "€ 9,99",
    image: product1Img,
  },
  {
    id: 7,
    name: "Sabonete para Barba",
    description: "Limpeza profunda com aroma refrescante.",
    price: "€ 11,50",
    image: product1Img,
  },
  {
    id: 8,
    name: "Loção Pós-Barba",
    description: "Refresca e acalma a pele irritada.",
    price: "€ 13,30",
    image: product1Img,
  },
  {
    id: 9,
    name: "Shampoo para Barba",
    description: "Limpa e hidrata os pelos faciais.",
    price: "€ 17,00",
    image: product1Img,
  },
  {
    id: 10,
    name: "Condicionador para Barba",
    description: "Amacia e facilita o penteado.",
    price: "€ 18,90",
    image: product1Img,
  },
  {
    id: 11,
    name: "Pente de Madeira",
    description: "Desembaraça sem danificar os fios.",
    price: "€ 7,80",
    image: product1Img,
  },
  {
    id: 12,
    name: "Escova para Barba",
    description: "Modela e ajuda na limpeza dos pelos.",
    price: "€ 14,00",
    image: product1Img,
  },
  {
    id: 13,
    name: "Kit Aparador de Barba",
    description: "Precisão e praticidade para o corte.",
    price: "€ 45,00",
    image: product1Img,
  },
  {
    id: 14,
    name: "Toalha Quente Facial",
    description: "Prepara a pele para o barbear.",
    price: "€ 20,00",
    image: product1Img,
  },
  {
    id: 15,
    name: "Creme Hidratante Facial",
    description: "Mantém a pele hidratada e saudável.",
    price: "€ 22,50",
    image: product1Img,
  },
  {
    id: 16,
    name: "Perfume Masculino",
    description: "Aroma sofisticado e marcante.",
    price: "€ 35,00",
    image: product1Img,
  },
  {
    id: 17,
    name: "Esfoliante Facial",
    description: "Remove células mortas e impurezas.",
    price: "€ 19,99",
    image: product1Img,
  },
  {
    id: 18,
    name: "Gel Refrescante para Olhos",
    description: "Reduz olheiras e inchaço.",
    price: "€ 16,75",
    image: product1Img,
  },
  {
    id: 19,
    name: "Protetor Solar Facial",
    description: "Proteção eficaz contra raios UV.",
    price: "€ 21,30",
    image: product1Img,
  },
  {
    id: 20,
    name: "Loção Anti-idade",
    description: "Previne sinais de envelhecimento.",
    price: "€ 28,00",
    image: product1Img,
  },
];
